---
- name: Vérifier l'état de sécurité et système de la machine Rocky Linux
  hosts: all
  become: yes
  gather_facts: yes  # Pour récupérer les infos système

  tasks:
    - name: Vérifier les mises à jour de sécurité (Critical & Important)
      shell: dnf updateinfo list security severity=Critical,Important || true
      register: dnf_security_updates
      changed_when: false

    - name: Extraire les lignes de mises à jour
      set_fact:
        update_lines: "{{ dnf_security_updates.stdout_lines | select('match', '^RHSA') | list }}"

    - name: Compter les mises à jour Critical
      set_fact:
        critical_updates: "{{ update_lines | select('search', 'Critical') | list | length }}"

    - name: Compter les mises à jour Important
      set_fact:
        important_updates: "{{ update_lines | select('search', 'Important') | list | length }}"

    - name: Récupérer l'uptime
      shell: awk '{print int($1/3600)"h "int(($1%3600)/60)"m"}' /proc/uptime
      register: system_uptime
      changed_when: false

    - name: Afficher le résumé système et sécurité
      debug:
        msg: |
          ✅ Informations système :
          - OS       : {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Uptime   : {{ system_uptime.stdout }}

          🔐 Mises à jour de sécurité :
          - Critiques : {{ critical_updates }}
          - Importantes : {{ important_updates }}
