---
- name: Vérifier les mises à jour critiques et importantes sur plusieurs distributions
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Déterminer la distribution Linux
      set_fact:
        os_family: "{{ ansible_os_family | lower }}"
        os_name: "{{ ansible_distribution | lower }}"

    - name: Afficher la version de l'OS
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Ubuntu/Debian - Récupérer les mises à jour de sécurité
      shell: |
        apt-get -s dist-upgrade | grep "^Inst" | grep -i security || true
      register: debian_updates
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Compter les mises à jour de sécurité (Debian)
      set_fact:
        debian_updates_count: "{{ debian_updates.stdout_lines | length }}"
      when: ansible_os_family == "Debian"

    - name: Afficher les mises à jour de sécurité Ubuntu/Debian
      debug:
        msg: |
          Nombre de mises à jour de sécurité : {{ debian_updates_count }}
          Détails :
          {% for pkg in debian_updates.stdout_lines %}
          - {{ pkg }}
          {% endfor %}
      when: ansible_os_family == "Debian"

    - name: RedHat/Fedora (RHEL, CentOS, Alma) - Récupérer les mises à jour critiques
      shell: dnf updateinfo list security | grep Critical || true
      register: critical_updates_raw
      changed_when: false
      when: os_family == "redhat"

    - name: RedHat/Fedora (RHEL, CentOS, Alma) - Récupérer les mises à jour importantes
      shell: dnf updateinfo list security | grep Important || true
      register: important_updates_raw
      changed_when: false
      when: os_family == "redhat"

    - name: Compter les mises à jour critiques (RedHat)
      set_fact:
        critical_count: "{{ critical_updates_raw.stdout_lines | length }}"
        critical_list: "{{ critical_updates_raw.stdout_lines }}"
      when: os_family == "redhat"

    - name: Compter les mises à jour importantes (RedHat)
      set_fact:
        important_count: "{{ important_updates_raw.stdout_lines | length }}"
        important_list: "{{ important_updates_raw.stdout_lines }}"
      when: os_family == "redhat"

    - name: Afficher les mises à jour critiques et importantes (RedHat)
      debug:
        msg: |
          {{ ansible_hostname }} ({{ ansible_distribution }}):
          Mises à jour CRITIQUES : {{ critical_count }}
          {% for pkg in critical_list %}
          - {{ pkg }}
          {% endfor %}

          Mises à jour IMPORTANTES : {{ important_count }}
          {% for pkg in important_list %}
          - {{ pkg }}
          {% endfor %}
      when: os_family == "redhat"
